### ISSUE TITLE
HSTS Warnings

### ISSUE THREAD

**Issue by jpillora** [unrolled/secure#1]
Forcing HTTPS on all subdomains for 10 years is a dangerous to show on the first example. There should probably be some kind of warning about HSTS - that once you add them and user's browsers accept them, they can't be removed. If this Go server is handling all subdomains, then it'll probably be fine, but many people will have CNAMEs pointing elsewhere for various hosted services, etc.

**Comment by gellerb** [comment]
* In general, the value of a year is used (31536000)
* @jpillora, HSTS can be removed by the sender sending `max-age=0`

**Comment by jpillora** [comment]
Though the removal needs to be served from HTTPS, so you wouldn't want to
accidentally enable HSTS with an HTTP only site - even for 1 year instead
of 10.

**Comment by gellerb** [comment]
If one accidentally enabled HSTS on an HTTP-only site nothing would happen. The application isn't listening on port 443 if it's an HTTP-only site and HSTS is only accepted over HTTPS. In other words, the browser ignores the HSTS header over HTTP even if the application provides it.

**Comment by jpillora** [comment]
Ah I thought I'd previously accidentally enabled it one time and was forced to go into chromes net internals to wipe it, my mistake

**Comment by unrolled** [comment]
I'm debating if it's a good idea to remove the`Strict-Transport-Security` header from HTTP requests to avoid confusion... but then again it's kind of a nice verification the headers are coming through properly when running on a non-secure localhost connection. Or maybe always add it when `isDevelopment` is true, otherwise only on HTTPS connections.

Thoughts @jpillora @gellerb ?

**Comment by jpillora** [comment]
For verification and to avoid magic behaviour, probably best to leave it as is, the extra few bytes won't hurt

**Comment by gellerb** [comment]
Per the spec at the bottom of  section 7.2[1].
"An HSTS Host MUST NOT include the STS header field in HTTP responses conveyed over non-secure transport."

[1] http://tools.ietf.org/html/rfc6797#section-7.2

**Comment by unrolled** [comment]
Thanks for digging that up @gellerb! I'm going to investigate and see how to best handle this.
