### ISSUE TITLE
Add support for "Referrer-Policy" header

### ISSUE THREAD

**Issue by kujenga** [unrolled/secure#13]
The "Referrer-Policy" header is recently introduced and adds support for global restrictions on referrer leakage. It would probably be useful to add support for it here! It's recently been added to the https://securityheaders.io testing website, with a corresponding blog post [1]. Is this something you would be open to?

[1] https://scotthelme.co.uk/a-new-security-header-referrer-policy/

**Comment by unrolled** [comment]
Absolutely! Are you interested in submitting a PR for this?
