### ISSUE TITLE
Allow for a proxy header to specify the Host

### ISSUE THREAD

**Issue by kujenga** [unrolled/secure#15]
A proxy like Apache transmits certain information over headers when in a reverse proxy configuration [1]. Currently, this repo supports the use of custom headers for detecting when SSL is enabled, via the `SSLProxyHeaders` option, but this functionality is not present for the `AllowedHosts` option.

I'm planning to submit a PR for this shortly.

[1] https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers

**Comment by unrolled** [comment]
Fixed, thanks!
