### ISSUE TITLE
Allow customization of the X-XSS-Protection header

### ISSUE THREAD

**Issue by F21** [unrolled/secure#19]
The following are valid values for the `X-XSS-Protection` header:

```
X-XSS-Protection: 0
X-XSS-Protection: 1
X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; report=<reporting-uri>
```
Setting `BrowserXssFilter` to true gives the header the value `1; mode=block`, but does not allow for setting it as `1` or `1; report=<reporting-uri>`.

It would be nice if there is the possibility of setting it to these values: `1` or `1; report=<reporting-uri>`.

**Comment by unrolled** [comment]
Good call. I'll add in a custom content type parameter like `CustomFrameOptionsValue`.

**Comment by unrolled** [comment]
I just added the `CustomBrowserXssValue` option. Let me know how it works out!

https://github.com/unrolled/secure/commit/a80c09da9c7bd84aaf622507fd339a9281b8acd1
