### ISSUE TITLE
Can't get $NONCE to work properly

### ISSUE THREAD

**Issue by daseinhorn** [unrolled/secure#29]
I'm currently trying to implement the new (and awesome) dynamic CSP nonce feature to work, but I think I'm doing something wrong.

I created a secure.Options struct with the following params:
`secureMiddlewareOptions := secure.Options{
ContentSecurityPolicy: "script-src $NONCE",
}`

I then add the created middleware to my main negroni route:
`secureMiddleware := secure.New(secureMiddlewareOptions)
n.Use(negroni.HandlerFunc(secureMiddleware.HandlerFuncWithNext))`

The `Content-Security-Policy` header is added correctly, and the $NONCE is replaced. But instead of replacing it with a random CSP "string" nothing is added. The result looks like this:
`Content-Security-Policy:script-src 'nonce-'`. 

Did I overlook something? Thanks for your help.

**Comment by unrolled** [comment]
Hmm, I just tried it out and everything looks good to me. Can you provide more details on what version of Go you're compiling with and what environment you're running on?

**Comment by daseinhorn** [comment]
I'm running `go version go1.9.2 darwin/amd64`. The problem is that the `strings.Replace` where the $NONCE gets replaced returns bad index.

**Comment by unrolled** [comment]
Ohhhh crap! I found the problem... When using the dynamic csp with the `HandlerFuncWithNext` method was totally broken. I just pushed a fix up that you can try out. Let me know if that fixes it for you!

**Comment by daseinhorn** [comment]
Sorry completely missed the notification! It works now. Thanks for the fix!
