### ISSUE TITLE
How to redirect from HTTP to HTTPS with CSP set?

### ISSUE THREAD

**Issue by ajeecai** [unrolled/secure#37]
Hi, I am seeking to redirect from HTTP to HTTPS, usually the browser may complain that mix-content after redirecting since the original page contains some static http link. Then I saw "Content-Security-Policy: upgrade-insecure-requests" could help from [this article](https://blog.cloudflare.com/fixing-the-mixed-content-problem-with-automatic-https-rewrites/). 

From the example in this README, I saw it could do the redirection and also there is CSP option, but when I try it out, it can work with redirection but there is no CSP option seen in the http header, what is wrong? 

Thanks

**Comment by unrolled** [comment]
Hey @ajeecai, can you send me a snippet of code with your set options? With that I can try and find out whats happening. Thanks!

**Comment by unrolled** [comment]
@ajeecai Going to close this for now, please reopen if you still need help. Thanks!!
