### ISSUE TITLE
Add support for Expect-CT security header

### ISSUE THREAD

**Issue by Yggdrasil** [unrolled/secure#41]
Please add support for the Expect-CT header. This header allows site admins to get reports from browsers if a received certificated doesn't contain valid Certificate Transparency information. Since CT is now required by all modern browsers this can help admins detect some misconfigurations.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT
https://scotthelme.co.uk/a-new-security-header-expect-ct/

The header is already checked (but not scored) by securityheaders.io.

**Comment by unrolled** [comment]
Done!

**Comment by Yggdrasil** [comment]
Holy cow, that's quick. Thanks very much!
