### ISSUE TITLE
How should I use CSP nonce with Gin?

### ISSUE THREAD

**Issue by hashworks** [unrolled/secure#43]
According to the README one should use secure with Gin using the `Process` function. However it [doesn't implement](https://github.com/unrolled/secure/blob/v1/secure.go#L215) the nonce generation [like the `Handler` function](https://github.com/unrolled/secure/blob/ff9db2ff917ff44b71a2e62c015f4c7e0e567929/secure.go#L179).

Should I use one of the Handler functions? If so, how?

**Comment by unrolled** [comment]
Hey @hashworks, sorry for the delay! I just pushed a fix that moves the nonce generation into the root process function. You should be good to go now.
