### ISSUE TITLE
Unexported `processRequest` does not allow modification of the request before next

### ISSUE THREAD

**Issue by dtomcej** [unrolled/secure#45]
Hello,

Here is the issue I am encountering:

We have a request that is passed to secure that has been modified by other middleware. The path has been modified, and therefore when passed to secure, the incorrect response is generated.

The solution as far as I see it, is to "unmodify" the path, pass the request to secure, then "remodify" the path after secure has processed the request, but before it passes to `next`. The issue I am encountering with secure is that `processRequest` is not exported, and therefore cannot be used by my package.

I am essentially trying to write my own `HandlerFuncForRequestOnly` (https://github.com/unrolled/secure/blob/v1/secure.go#L183).
Do you think that `processRequest` could be exported?

Or do you think that we could have a mirrored `ProcessNoModifyRequest` similar to `Process` that returns the responseHeaders? something like this:

```go
// ProcessNoModifyRequest runs the actual checks but does not write the headers in the ResponseWriter.
func (s *Secure) ProcessNoModifyRequest(w http.ResponseWriter, r *http.Request) (http.Header, error) {
	return s.processRequest(w, r)
}
```

Thoughts?

**Comment by unrolled** [comment]
Hey @dtomcej I'm liking the second option more than the first... I think something like your `ProcessNoModifyRequest` function example would be the better solution. Do you want to whip up a PR?

**Comment by dtomcej** [comment]
Absolutely,
will have one created shortly.
