### ISSUE TITLE
500 error when redirecting from http to https on HEAD requests

### ISSUE THREAD

**Issue by BrodrickChilds** [unrolled/secure#5]
Using this code to set up our secure:
    securer := secure.Secure(secure.Options{
		SSLRedirect:          strings.ToLower(os.Getenv("FORCE_SSL")) == "true",
		SSLProxyHeaders:      map[string]string{"X-Forwarded-Proto": "https"},
		STSSeconds:           315360000,
		STSIncludeSubdomains: true,
		FrameDeny:            true,
		ContentTypeNosniff:   true,
		BrowserXssFilter:     true,
	})

Always getting 500 errors on HEAD requests to http://[website] when it tries to redirect to https.  Is this a known issue? Is there some configuration to get around this?  Thanks!

**Comment by unrolled** [comment]
Here's the test I wrote for this:

``` go
func TestSSLRedirectOnHeadRequest(t *testing.T) {
	s := New(Options{
		SSLRedirect: true,
		SSLProxyHeaders: map[string]string{"X-Forwarded-Proto": "https"},
		STSSeconds: 315360000,
		STSIncludeSubdomains: true,
		FrameDeny: true,
		ContentTypeNosniff: true,
		BrowserXssFilter: true,
		IsDevelopment: false,
	})

	res := httptest.NewRecorder()
	req, _ := http.NewRequest("HEAD", "/foo", nil)
	req.Host = "www.example.com"
	req.URL.Scheme = "http"

	s.Handler(myHandler).ServeHTTP(res, req)

	expect(t, res.Code, http.StatusMovedPermanently)
	expect(t, res.Header().Get("Location"), "https://www.example.com/foo")
}
```
So this test passes... does this mimic your request? I might need some more code to help you debug this.
