### ISSUE TITLE
AllowedHost check wildcard for subdomains

### ISSUE THREAD

**Issue by pzeinlinger** [unrolled/secure#50]
In my opinion, the if clause for the host check should rather be implemented with a regular expression, since e.g. wildcards are often used to allow subdomains.

What's your point of view on this issue? Should I open a pull request?

**Comment by unrolled** [comment]
I think that's a valid point. If you can implement it with backwards compatibility that would be awesome!

**Comment by pzeinlinger** [comment]
I opted for a new options flag, because just changing the string check to a regex match would essentially compromise security (e.g. sub1example.com would come back valid for sub.example.com).
The implementation uses regex compile to speed up checks.

**Comment by unrolled** [comment]
Thanks for putting this together!
