### ISSUE TITLE
use for microservices facing public 

### ISSUE THREAD

**Issue by mlevkov** [unrolled/secure#53]
Hello,

Not entirely an issues, but rather a question of use. Could I use this library to strengthen security of access for a publicly facing REST API microservice?

Also, once implemented, is there is a way to validate options manually that they are enabled and properly functioning?

Regards,
Max

**Comment by unrolled** [comment]
Yes, this package would help secure a public REST API. You can enable it with the config options you want, and for the most part you can verify the functionality by looking at the HTTP headers in the response, as well as just manually testing any redirects.
