### ISSUE TITLE
不能用443端口吗？

### ISSUE THREAD

**Issue by heroghost** [unrolled/secure#60]
我把gin代码示例里的端口改成443端口，然后访问不了，说找不到网页。

**Comment by unrolled** [comment]
Did you add certs and try it with `https`?

**Comment by heroghost** [comment]
Yes, I added certs from Nginx.
	r.Use(LoadTls())
	//r.RunTLS(":443", "mini.qubaozhuang.cn-crt.pem", "mini.qubaozhuang.cn-key.pem")
	r.RunTLS(":443", "2908101.pem", "2908101.key")
	//r.Run("127.0.0.1:80") // listen and serve on 0.0.0.0:8080
}

func LoadTls() gin.HandlerFunc {
	return func(c *gin.Context) {
		middleware := secure.New(secure.Options{
			SSLRedirect: true,
			SSLHost:     "127.0.0.1:443",
		})
		err := middleware.Process(c.Writer, c.Request)
		if err != nil {
			//如果出现错误，请不要继续。
			fmt.Println(err)
			return
		}
		// 继续往下处理
		c.Next()
	}
}

**Comment by heroghost** [comment]
Yes, I added certs from Nginx. 
	r.Use(LoadTls())
	r.RunTLS(":443", "2908101.pem", "2908101.key")
}

func LoadTls() gin.HandlerFunc {
	return func(c *gin.Context) {
		middleware := secure.New(secure.Options{
			SSLRedirect: true,
			SSLHost:     "127.0.0.1:443",
		})
		err := middleware.Process(c.Writer, c.Request)
		if err != nil {
			//如果出现错误，请不要继续。
			fmt.Println(err)
			return
		}
		// 继续往下处理
		c.Next()
	}
}

**Comment by unrolled** [comment]
I ran the following and it all worked for me, give this a try:

Generate new self signed cert:
```bash
openssl req -newkey rsa:2048 \
  -new -nodes -x509 \
  -days 3650 \
  -out cert.pem \
  -keyout key.pem \
  -subj "/C=US/ST=California/L=Mountain View/O=Your Organization/OU=Your Unit/CN=localhost"
```

Sample go app:
```go
package main

import (
	"github.com/gin-gonic/gin"
	"github.com/unrolled/secure"
)

func main() {
	secureMiddleware := secure.New(secure.Options{
		FrameDeny:   true,
		SSLRedirect: true,
		SSLHost:     "localhost:443",
	})
	secureFunc := func() gin.HandlerFunc {
		return func(c *gin.Context) {
			err := secureMiddleware.Process(c.Writer, c.Request)

			// If there was an error, do not continue.
			if err != nil {
				c.Abort()
				return
			}

			// Avoid header rewrite if response is a redirection.
			if status := c.Writer.Status(); status > 300 && status < 399 {
				c.Abort()
			}
		}
	}()

	router := gin.Default()
	router.Use(secureFunc)

	router.GET("/", func(c *gin.Context) {
		c.String(200, "Hello SSL")
	})

	router.RunTLS(":443", "cert.pem", "key.pem")
}
```

Head to `https://localhost`, accept the certificate (in Chrome anyway), and you should see the page come up.

**Comment by heroghost** [comment]
Yes, The problem has been solved by follow your step to generate the cert. It must be the cert for nginx can't use for the program. I should find out the difference between the certs. Thank you very much!
