### ISSUE TITLE
Bad Host (Cloudflare)

### ISSUE THREAD

**Issue by misterr8472** [unrolled/secure#66]
Hello, 

I am proxied behind Cloudflare. I Set SSLHost to a number of variations of "https://url.example.co.uk", "https://url.example.co.uk/", "url.example.co.uk", but I keep getting "bad host" at my staging environment.

I should note that my dev environment is working fine, but that's because I've set the IsDevelopment param to true.

I don't think I had this issue before proxying via CloudFlare, so now I am wondering whether that may have caused it. I have also passed all URLs of my project to "AllowedHosts", so technically that should work. 

I am slightly lost and was wondering whether you may be able to offer some help. Thanks!

**Comment by unrolled** [comment]
You may have to set `SSLProxyHeaders: map[string]string{"X-Forwarded-Proto": "https"},` in the config so that the middleware knows we are secure already (https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-)

**Comment by misterr8472** [comment]
I must apologise, I realised I set the allowed hosts wrong. I included "https://" with them, which didn't work. Without them it's fine. 
It is worth noting that Mozilla Observatory reports that it does not recognise the HSTS header, even though I have explicitly set that.
