### ISSUE TITLE
WSS support

### ISSUE THREAD

**Issue by yanfali** [unrolled/secure#7]
I'm trying to use unrolled secure for CSP support, but I'm finding the static configuration a little inflexible when trying to configure for websockets. Would there be interest in a new configuration option to support websockets in the connect-src option that was slightly more dynamic?

for websockets the policy looks like `connect-src wss://theserver`. Since the configuration is statically configured at middleware construction time, and it's hard to know what IP the server is actually serving from until runtime; especially with reverse proxys and containers, etc, this makes it hard to achieve with the current middleware.

Options:

1. write a new middleware and not use the CSP option in unrolled/secure
2. write code which allows dynamic insertion of WSS/WS using the incoming request's Host value.

Would there be interest in take a PR which implemented something like option 2? or should I just go with something like option 1?

Thanks for writing a very useful middleware!

**Comment by unrolled** [comment]
Hey, thanks for opening this issue!

This is an interesting problem and I can see the appeal of option 2. But I would prefer option 1... I'm not a fan of making middleware packages dynamic. If you do write a new middleware, I'd be more than happy to include the link and description on the readme!

Cheers,
Cory

**Comment by yanfali** [comment]
Thanks for the feedback. I did implement another middleware, let me see if I can't clean it up a bit and open source it for you to reference.
