### ISSUE TITLE
Panic when accession newR.Context()

### ISSUE THREAD

**Issue by ScottBrooks** [unrolled/secure#70]
When s.processRequest returns an error, newR is nil, and `newR.Context()` panics

https://github.com/unrolled/secure/blob/ab726b2507016220542feb9ca0fa1d7c94801bc4/secure.go#L252-L255

**Comment by unrolled** [comment]
Good catch! I'll fix that up right away, thanks!

**Comment by ScottBrooks** [comment]
Thanks!
