### ISSUE TITLE
Support for Access-Control-Allow-Origin headers?

### ISSUE THREAD

**Issue by bramp** [unrolled/secure#72]
Worth adding support for Access-Control-Allow-Origin headers? Perhaps even reusing the AllowedHost list?

**Comment by unrolled** [comment]
There are a bunch of Access-Control-* headers we could add... what is we did the same concept as #73 and create a helper to generate the output... something like: 
```go
secure.Options{
  AccessControl: secure.AccessControlOptions{
    AllowCredentials: true,
    AllowHeaders: ["DNT", "User-Agent", "Cache-Control", "Content-Type"],
    AllowMethods: ["GET", "POST", "OPTIONS"],
    AllowOrigin: "*",
    ExposeHeaders: ["Cache-Control", "Content-Language", "Content-Length", "Content-Type"]
    MaxAge: 1728000,
    RequestHeaders: ["X-PINGOTHER", "Content-Type"],
    RequestMethod: ["POST"],
  }
}

```

**Comment by emarais-godaddy** [comment]
@unrolled Is there a branch with these CORS options in or have you abandoned the idea of adding it to the lib? I can't seem to find the options in the repo atm. 🙏🏻

**Comment by unrolled** [comment]
Hey @emarais-godaddy, this hasn't been implemented yet. I still like the idea but haven't had the time to work on it. Would love some help if you (or anyone else) has time!
