### ISSUE TITLE
SQL Injection detection based on payload

### ISSUE THREAD

**Issue by batara666** [unrolled/secure#78]

**Comment by emarais-godaddy** [comment]
@batara666 I am interested to hear what you would do for such a feature? It might be valuable to everyone if you elaborate on some of your ideas here please? 🙏🏻

**Comment by batara666** [comment]
for example, Cloudflare

if `' or ''='` are detected on a request payload, Cloudflare will block the request

**Comment by unrolled** [comment]
I'm going to close this as I'm not sure such a feature belongs in this package.
